# Generated by Django 5.0 on 2024-03-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_order_customer_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Uncategorized', max_length=100),
        ),
    ]
