# Generated by Django 5.0 on 2024-03-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='date_deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
