# Generated by Django 5.0 on 2024-03-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_orderitem_date_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='date_deleted',
        ),
    ]
