# Generated by Django 5.0 on 2024-03-31 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
