# Generated by Django 5.0 on 2024-04-01 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
