# Generated by Django 5.0 on 2024-04-01 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
