# Generated by Django 5.0 on 2024-04-01 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_product_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='detail',
        ),
    ]
