# Generated by Django 5.0 on 2024-04-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_ingredient',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
